'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowUpRight, ChevronDown, Clapperboard, FileText, Mail, Menu, MessageCircle, Music2, Play, X } from 'lucide-react'

type Language = 'en' | 'fr' | 'ar'

type Project = { title: string; category: string; type: string; image: string; description: string }

const projectImages = [
  'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=1200&q=85',
  'https://images.unsplash.com/photo-1558655146-9f40138edfeb?auto=format&fit=crop&w=1200&q=85',
  'https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?auto=format&fit=crop&w=1400&q=85',
  'https://images.unsplash.com/photo-1536240478700-b869070f9279?auto=format&fit=crop&w=1200&q=85',
  'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1200&q=85',
]

const translations = {
  en: {
    nav: ['Work', 'Services', 'About', 'Contact'], cta: "Let's Work Together", editor: 'Freelance video editor', hero: <>I turn raw footage into <em>content people want to watch.</em></>, heroText: 'Video editing for social media, podcasts, YouTube, and digital content.', viewWork: 'View My Work', showreel: 'View showreel', desk: 'The edit desk', selected: 'Selected Work', selectionNote: 'A small selection of cuts, stories, and visual systems.', all: 'All', toolkit: 'The toolkit', what: 'What I Do', aboutEyebrow: 'A little about me', aboutTitle: <>Good edits make the story feel <em>effortless.</em></>, about1: "I'm Noureddine Bouderbala, a video editor focused on creating engaging and visually polished content.", about2: 'I turn raw footage into clear, dynamic, and engaging videos with a focus on pacing, storytelling, and attention to detail.', start: 'Start a project', contactTitle: <>Have a project<br />in mind?</>, contactText: "Send me the details and let's talk.", name: 'Name', email: 'Email', projectType: 'Project Type', select: 'Select a project type', message: 'Message', messagePlaceholder: 'Tell me a little about your project...', send: 'Send Inquiry', photo: 'Photo placeholder', footer: 'Video Editor & Visual Storyteller', types: ['Short-form', 'Podcast', 'YouTube', 'Motion Graphics', 'Social Media', 'Other'], filters: ['All', 'Short Form', 'Podcast', 'YouTube', 'Motion Graphics', 'Social Media'], metrics: ['TOTAL VIEWS', 'FOLLOWERS GROWTH', 'VIDEOS / EDITS', 'YEARS CREATING'], projects: [['Good Sleep Habits', 'Podcast', 'Podcast Editing', 'A warm, conversational edit built around clean pacing and clear storytelling.'], ['Before / After', 'Short Form', 'Short-Form Editing', 'A punchy social cut with a strong hook, quick rhythm, and purposeful captions.'], ['UI Style Animation', 'Motion Graphics', 'Motion Graphics', 'A polished interface animation designed to make product ideas feel tangible.'], ['The Creator Playbook', 'YouTube', 'YouTube Editing', 'Long-form storytelling with considered pacing, B-roll, and visual resets.'], ['Build In Public', 'Social Media', 'Social Media', 'A vertical content system that turns one idea into a series of engaging clips.'], ['A Quiet Morning', 'Short Form', 'Short-Form Editing', 'Atmospheric editing where sound, texture, and timing carry the story.']], services: [['Short-Form Editing', 'Reels, TikToks, and YouTube Shorts.'], ['Podcast Editing', 'Podcast clips with captions, B-roll, and sound design.'], ['YouTube Editing', 'Engaging long-form video editing.'], ['Motion Graphics', 'Animations, titles, transitions, and visual effects.']] },
  fr: {
    nav: ['Travail', 'Services', 'À propos', 'Contact'], cta: 'Travaillons ensemble', editor: 'Monteur vidéo freelance', hero: <>Je transforme vos rushes en <em>contenus que l’on veut regarder.</em></>, heroText: 'Montage vidéo pour les réseaux sociaux, podcasts, YouTube et contenus digitaux.', viewWork: 'Voir mon travail', showreel: 'Voir le showreel', desk: 'La table de montage', selected: 'Travaux sélectionnés', selectionNote: 'Une sélection de montages, récits et systèmes visuels.', all: 'Tout', toolkit: 'La boîte à outils', what: 'Ce que je fais', aboutEyebrow: 'À propos de moi', aboutTitle: <>Un bon montage rend l’histoire <em>naturelle.</em></>, about1: 'Je suis Noureddine Bouderbala, monteur vidéo spécialisé dans la création de contenus engageants et soignés.', about2: 'Je transforme vos rushes en vidéos claires et dynamiques, avec une attention particulière au rythme, au storytelling et aux détails.', start: 'Démarrer un projet', contactTitle: <>Un projet<br />en tête ?</>, contactText: 'Envoyez-moi les détails et parlons-en.', name: 'Nom', email: 'E-mail', projectType: 'Type de projet', select: 'Choisir un type de projet', message: 'Message', messagePlaceholder: 'Parlez-moi un peu de votre projet...', send: 'Envoyer la demande', photo: 'Photo à venir', footer: 'Monteur vidéo & storyteller visuel', types: ['Format court', 'Podcast', 'YouTube', 'Motion design', 'Réseaux sociaux', 'Autre'], filters: ['Tout', 'Format court', 'Podcast', 'YouTube', 'Motion design', 'Réseaux sociaux'], metrics: ['VUES TOTALES', 'CROISSANCE ABONNÉS', 'VIDÉOS / MONTAGES', 'ANNÉES DE CRÉATION'], projects: [['Bonnes habitudes de sommeil', 'Podcast', 'Montage podcast', 'Un montage chaleureux et conversationnel, construit autour d’un rythme fluide.'], ['Avant / Après', 'Format court', 'Montage format court', 'Une vidéo sociale rythmée avec une accroche forte et des sous-titres utiles.'], ['Animation UI', 'Motion design', 'Motion design', 'Une animation d’interface soignée pour rendre les idées produit concrètes.'], ['Le guide du créateur', 'YouTube', 'Montage YouTube', 'Un récit long format avec rythme, B-roll et respirations visuelles.'], ['Construire en public', 'Réseaux sociaux', 'Réseaux sociaux', 'Un système vertical qui transforme une idée en série de clips engageants.'], ['Un matin calme', 'Format court', 'Montage format court', 'Un montage atmosphérique où le son, la texture et le timing racontent l’histoire.']], services: [['Montage format court', 'Reels, TikToks et YouTube Shorts.'], ['Montage podcast', 'Clips podcast avec sous-titres, B-roll et sound design.'], ['Montage YouTube', 'Montage vidéo long format et engageant.'], ['Motion design', 'Animations, titres, transitions et effets visuels.']] },
  ar: {
    nav: ['الأعمال', 'الخدمات', 'من أنا', 'تواصل'], cta: 'لنعمل معًا', editor: 'محرر فيديو مستقل', hero: <>أحوّل اللقطات الخام إلى <em>محتوى يستحق المشاهدة.</em></>, heroText: 'مونتاج فيديو لمنصات التواصل، البودكاست، يوتيوب والمحتوى الرقمي.', viewWork: 'شاهد أعمالي', showreel: 'شاهد العرض', desk: 'على طاولة المونتاج', selected: 'أعمال مختارة', selectionNote: 'مجموعة مختارة من المونتاج والقصص والأنظمة البصرية.', all: 'الكل', toolkit: 'الأدوات', what: 'ما أقدمه', aboutEyebrow: 'نبذة عني', aboutTitle: <>المونتاج الجيد يجعل القصة تبدو <em>سلسة.</em></>, about1: 'أنا نورالدين بودربالة، محرر فيديو أركز على صناعة محتوى جذاب ومتقن بصريًا.', about2: 'أحوّل اللقطات الخام إلى فيديوهات واضحة وحيوية، مع التركيز على الإيقاع والسرد والاهتمام بالتفاصيل.', start: 'ابدأ مشروعًا', contactTitle: <>هل لديك مشروع<br />في ذهنك؟</>, contactText: 'أرسل لي التفاصيل لنتحدث.', name: 'الاسم', email: 'البريد الإلكتروني', projectType: 'نوع المشروع', select: 'اختر نوع المشروع', message: 'الرسالة', messagePlaceholder: 'أخبرني قليلًا عن مشروعك...', send: 'إرسال الطلب', photo: 'الصورة قريبًا', footer: 'محرر فيديو وصانع قصص بصرية', types: ['فيديو قصير', 'بودكاست', 'يوتيوب', 'موشن جرافيك', 'تواصل اجتماعي', 'أخرى'], filters: ['الكل', 'فيديو قصير', 'بودكاست', 'يوتيوب', 'موشن جرافيك', 'تواصل اجتماعي'], metrics: ['إجمالي المشاهدات', 'نمو المتابعين', 'فيديو / مونتاج', 'سنوات من الإبداع'], projects: [['عادات النوم الجيدة', 'بودكاست', 'مونتاج بودكاست', 'مونتاج دافئ وحواري مبني على إيقاع واضح وسرد سلس.'], ['قبل / بعد', 'فيديو قصير', 'مونتاج قصير', 'مقطع اجتماعي سريع بخطاف قوي وإيقاع جذاب وترجمة هادفة.'], ['رسوم واجهة المستخدم', 'موشن جرافيك', 'موشن جرافيك', 'تحريك أنيق للواجهة يجعل أفكار المنتج ملموسة.'], ['دليل صانع المحتوى', 'يوتيوب', 'مونتاج يوتيوب', 'سرد طويل بإيقاع مدروس ولقطات مساندة وانتقالات بصرية.'], ['البناء أمام الجمهور', 'تواصل اجتماعي', 'تواصل اجتماعي', 'نظام محتوى عمودي يحوّل الفكرة إلى سلسلة من المقاطع الجذابة.'], ['صباح هادئ', 'فيديو قصير', 'مونتاج قصير', 'مونتاج هادئ يحمل فيه الصوت والملمس والتوقيت القصة.']], services: [['مونتاج الفيديو القصير', 'ريلز وتيك توك ويوتيوب شورتس.'], ['مونتاج البودكاست', 'مقاطع بودكاست مع ترجمة ولقطات مساندة وتصميم صوتي.'], ['مونتاج يوتيوب', 'مونتاج فيديو طويل وممتع.'], ['موشن جرافيك', 'تحريك وعناوين وانتقالات وتأثيرات بصرية.']] },
} as const

const metricValues = ['1M+', '50K+', '100+', '3+']

const contactLinks = {
  cv: '/cv.pdf',
  whatsapp: 'https://wa.me/?text=Hello%20NXR%20Studio%2C%20I%27d%20like%20to%20discuss%20a%20project.',
  youtube: 'https://www.youtube.com/@nxrstudio',
  tiktok: 'https://www.tiktok.com/@nxrstudio',
}

export default function Page() {
  const [language, setLanguage] = useState<Language>('en')
  const [activeFilter, setActiveFilter] = useState(0)
  const [selectedProject, setSelectedProject] = useState<Project | null>(null)
  const [menuOpen, setMenuOpen] = useState(false)
  const t = translations[language]
  const projects = useMemo(() => t.projects.map((p, index) => ({ title: p[0], category: p[1], type: p[2], description: p[3], image: projectImages[index] })), [t])

  useEffect(() => {
    const saved = window.localStorage.getItem('nxr-language') as Language | null
    const detected = navigator.language.toLowerCase().startsWith('fr') ? 'fr' : navigator.language.toLowerCase().startsWith('ar') ? 'ar' : 'en'
    setLanguage(saved === 'en' || saved === 'fr' || saved === 'ar' ? saved : detected)
  }, [])

  useEffect(() => {
    document.documentElement.lang = language
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'
  }, [language])

  const chooseLanguage = (next: Language) => { setLanguage(next); window.localStorage.setItem('nxr-language', next) }
  const filteredProjects = activeFilter === 0 ? projects : projects.filter((project) => project.category === t.filters[activeFilter])
  const closeMenu = () => setMenuOpen(false)

  return <main className="site-shell">
    <nav className="nav" aria-label="Main navigation"><a href="#top" className="brand" onClick={closeMenu}>NXR<span>Studio</span></a><div className={`nav-links ${menuOpen ? 'is-open' : ''}`}>{t.nav.map((item, index) => <a href={['#work', '#services', '#about', '#contact'][index]} key={item} onClick={closeMenu}>{item}</a>)}<a className="nav-cta" href="#contact" onClick={closeMenu}>{t.cta} <ArrowUpRight size={15} /></a></div><div className="language-switcher" aria-label="Language selector">{(['en', 'fr', 'ar'] as Language[]).map((item) => <button key={item} className={language === item ? 'active' : ''} onClick={() => chooseLanguage(item)}>{item.toUpperCase()}</button>)}</div><button className="menu-button" aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></nav>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-dot" /> {t.editor}</p><h1>{t.hero}</h1><p className="hero-text">{t.heroText}</p><div className="hero-actions"><a className="button button-primary" href="#work">{t.viewWork} <ArrowUpRight size={17} /></a><a className="button button-ghost" href="#contact">{t.cta}</a><a className="button button-ghost" href={contactLinks.cv} download><FileText size={16} /> CV</a></div></div><a href="#work" className="showreel" aria-label={t.showreel}><img src="https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1600&q=85" alt="Film camera in a dark studio" /><span className="showreel-overlay"><span className="play-button"><Play fill="currentColor" size={18} /></span><span>{t.showreel}</span></span><span className="reel-index">01 / 06</span></a></section>
    <section className="metrics" aria-label="Studio metrics">{metricValues.map((value, index) => <div key={value}><strong>{value}</strong><span>{t.metrics[index]}</span></div>)}</section>
    <section className="work-section section" id="work"><div className="section-heading"><div><p className="eyebrow">{t.desk}</p><h2>{t.selected}</h2></div><p className="section-note">{t.selectionNote}</p></div><div className="filters" role="tablist" aria-label="Filter projects">{t.filters.map((filter, index) => <button key={filter} className={activeFilter === index ? 'active' : ''} onClick={() => setActiveFilter(index)}>{filter}</button>)}</div><div className="work-grid">{filteredProjects.map((project, index) => <button className={`project-card ${index === 0 ? 'featured' : ''}`} key={project.title} onClick={() => setSelectedProject(project)}><span className="project-image"><img src={project.image} alt="" /><span className="project-play"><Play fill="currentColor" size={15} /></span></span><span className="project-meta"><span><strong>{project.title}</strong><small>{project.type}</small></span><ArrowUpRight size={18} /></span></button>)}</div></section>
    <section className="services-section section" id="services"><div className="section-heading"><div><p className="eyebrow">{t.toolkit}</p><h2>{t.what}</h2></div></div><div className="service-list">{t.services.map(([title, description], index) => <div className="service-row" key={title}><span className="service-number">0{index + 1}</span><h3>{title}</h3><p>{description}</p><ArrowUpRight size={19} /></div>)}</div></section>
    <section className="about-section section" id="about"><div className="about-image"><div className="about-placeholder"><Clapperboard size={34} strokeWidth={1.3} /><span>{t.photo}</span></div></div><div className="about-copy"><p className="eyebrow">{t.aboutEyebrow}</p><h2>{t.aboutTitle}</h2><p>{t.about1}</p><p>{t.about2}</p></div></section>
    <section className="contact-section section" id="contact"><div className="contact-intro"><p className="eyebrow">{t.start}</p><h2>{t.contactTitle}</h2><p>{t.contactText}</p><div className="social-links"><a href={contactLinks.whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={18} /> WhatsApp</a><a href={contactLinks.youtube} target="_blank" rel="noreferrer"><Clapperboard size={18} /> YouTube</a><a href={contactLinks.tiktok} target="_blank" rel="noreferrer"><Music2 size={18} /> TikTok</a><a href="mailto:hello@nxrstudio.com"><Mail size={18} /> Email</a></div></div><form className="contact-form" action="https://formsubmit.co/hello@nxrstudio.com" method="POST"><input type="hidden" name="_subject" value="New project inquiry — NXR Studio" /><label>{t.name}<input required name="name" placeholder={t.name} /></label><label>{t.email}<input required type="email" name="email" placeholder="you@email.com" /></label><label>{t.projectType}<select required name="projectType" defaultValue=""><option value="" disabled>{t.select}</option>{t.types.map((type) => <option key={type}>{type}</option>)}</select><ChevronDown className="select-icon" size={16} /></label><label>{t.message}<textarea required name="message" rows={4} placeholder={t.messagePlaceholder} /></label><button className="button button-primary" type="submit">{t.send} <ArrowUpRight size={17} /></button></form></section>
    <footer className="footer"><div><a href="#top" className="brand">NXR<span>Studio</span></a><p>{t.footer}</p></div><div className="footer-right"><div className="footer-socials"><a href={contactLinks.whatsapp} target="_blank" rel="noreferrer">WhatsApp</a><a href={contactLinks.youtube} target="_blank" rel="noreferrer">YouTube</a><a href={contactLinks.tiktok} target="_blank" rel="noreferrer">TikTok</a><a href={contactLinks.cv} download>CV</a><a href="mailto:hello@nxrstudio.com">Email</a></div><p>© 2026 NXR Studio</p></div></footer>
    {selectedProject && <div className="modal-backdrop" role="presentation" onClick={() => setSelectedProject(null)}><div className="project-modal" role="dialog" aria-modal="true" aria-label={selectedProject.title} onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setSelectedProject(null)} aria-label="Close project"><X size={20} /></button><div className="modal-video"><img src={selectedProject.image} alt="" /><span className="modal-play"><Play fill="currentColor" size={25} /></span></div><p className="eyebrow">{selectedProject.type}</p><h2>{selectedProject.title}</h2><p>{selectedProject.description}</p></div></div>}
  </main>
}
